name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装编译工具
      run: sudo apt update && sudo apt install -y gcc

    - name: 编译 C 代码
      run: |
        # 假设 `main.c` 是包含 `main` 函数的文件，调整为适合你项目的文件名
        gcc -o my_program main.c utils.c math.c

    - name: 运行程序（可选）
      run: ./my_program
