name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装编译工具
      run: sudo apt update && sudo apt install -y gcc

    - name: 编译 C 代码
      run: |
        # 确保编译正确的文件
        gcc -o my_program aac2.c

    - name: 运行程序（可选）
      run: ./my_program
